<?php
/**
 * Generated by Haxe 4.3.3
 */

use \php\Boot;

class Main {
	/**
	 * @return void
	 */
	public static function main () {
	}

	/**
	 * @return void
	 */
	public function __construct () {
	}
}

Boot::registerClass(Main::class, 'Main');
