<?php
/**
 * Generated by Haxe 4.3.3
 */

namespace src\order\extra;

use \php\Boot;
use \src\infrastructure\BaseItem;

class Extra extends BaseItem {
	/**
	 * @return void
	 */
	public function __construct () {
		#src/order/extra/Extra.hx:7: characters 1-32
		parent::__construct();
	}
}

Boot::registerClass(Extra::class, 'src.order.extra.Extra');
