<?php
/**
 * Generated by Haxe 4.3.4
 */

namespace src\infrastructure;

use \php\Boot;

class Helper {
	/**
	 * @param float $totalNetValue
	 * 
	 * @return float
	 */
	public function formatReturnToPHP ($totalNetValue) {
		#src/infrastructure/Helper.hx:19: characters 3-59
		$formatter = new \NumberFormatter("en_US", 0, "#.##");
		#src/infrastructure/Helper.hx:20: characters 3-86
		$formatter->setAttribute(\NumberFormatter::ROUNDING_MODE, \NumberFormatter::ROUND_HALFUP);
		#src/infrastructure/Helper.hx:21: characters 3-63
		$totalNetValueFormated = $formatter->format($totalNetValue);
		#src/infrastructure/Helper.hx:22: characters 3-47
		return \Std::parseFloat($totalNetValueFormated);
	}
}

Boot::registerClass(Helper::class, 'src.infrastructure.Helper');
