<?php
/**
 * Generated by Haxe 4.3.3
 */

namespace src\order\pizza;

use \php\Boot;

class Flavor {
	/**
	 * @var float
	 */
	public $price;
	/**
	 * @var int
	 */
	public $quantity;

	/**
	 * @return void
	 */
	public function __construct () {
		#src/order/pizza/Flavor.hx:7: characters 28-29
		$this->quantity = 1;
		#src/order/pizza/Flavor.hx:6: characters 27-28
		$this->price = 0;
	}

	/**
	 * @param float $price
	 * 
	 * @return void
	 */
	public function addPrice ($price) {
		#src/order/pizza/Flavor.hx:12: characters 3-21
		$this->price = $price;
	}

	/**
	 * @param int $quantity
	 * 
	 * @return void
	 */
	public function addQuantity ($quantity) {
		#src/order/pizza/Flavor.hx:16: characters 3-27
		$this->quantity = $quantity;
	}
}

Boot::registerClass(Flavor::class, 'src.order.pizza.Flavor');
